name: app_maps_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_map: ^5.0.0
  flutter_native_splash: ^2.3.1
  formz: ^0.6.0
  geolocator: ^9.0.2
  go_router: ^9.0.3
  google_maps_flutter: ^2.5.0
  google_sign_in: ^6.1.4
  http: ^1.1.0
  latlong2: ^0.9.0
  provider: ^6.0.5
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/

flutter_native_splash:
  image: 'assets/image.png'
  color: '#FFFFFF'
